var originDataMovie = [
  { name: "Ha ha ha ha", value: 652 },
  { name: "ahhh", value: 87 },
  { name: "awesome", value: 58 },
  { name: "The world", value: 29 },
  { name: "beautiful", value: 26 },
  { name: "Oh my god", value: 24 },
  { name: "The wife", value: 21 },
  { name: "silky", value: 33 },
  { name: "The sequel", value: 17 },
  { name: "Too perfect", value: 35 },
  { name: "Come again", value: 27 },
  { name: "Million times", value: 13 },
  { name: "nice", value: 12 },
  { name: "dad", value: 11 },
  { name: "treasure found", value: 22 },
  { name: "system", value: 11 },
  { name: "The fairy", value: 10 },
  { name: "rebellious", value: 10 },
  { name: "subsequent", value: 22 },
  { name: "subscribe, like and share", value: 13 },
  { name: "black", value: 10 },
  { name: "What a guy", value: 8 },
  { name: "killed", value: 7 },
  { name: "Help!", value: 7 },
  { name: "Dove", value: 7 },
  { name: "Must", value: 6 },
  { name: "The plot", value: 6 },
  { name: "Your coin", value: 6 },
  { name: "evil", value: 5 },
  { name: "supporting actor", value: 5 },
  { name: "protagonist", value: 5 },
  { name: "routine", value: 5 },
  { name: "polite", value: 5 },
  { name: "congratulations", value: 5 },
  { name: "Sweet", value: 9 },
  { name: "master", value: 5 },
  { name: "like", value: 5 },
  { name: "wow", value: 9 },
  { name: "By chance", value: 5 },
  { name: "easy", value: 5 },
  { name: "clip", value: 5 },
  { name: "ecstasy", value: 5 },
  { name: "directly", value: 5 },
  { name: "Mrs.", value: 4 },
  { name: "know", value: 4 },
  { name: "original drama", value: 4 },
  { name: "marry", value: 8 },
  { name: "see", value: 4 },
  { name: "video", value: 4 },
  { name: "Every day,", value: 4 },
  { name: "Couldn't go out", value: 4 },
  { name: "Please add me as a friend", value: 4 },
  { name: "linkage", value: 4 },
  { name: "double fans", value: 4 },
  { name: "too much", value: 4 },
  { name: "feeling", value: 4 },
  { name: "2 times", value: 3 },
  { name: "crying", value: 3 },
  { name: "The author", value: 3 },
  { name: "Zhang Zhehan", value: 3 },
  { name: "really", value: 3 },
  { name: "good setting", value: 6 },
  { name: "hot", value: 3 },
  { name: "happy", value: 3 },
  { name: "dubbing", value: 3 },
  { name: "lovely", value: 3 },
  { name: "fantastic", value: 3 },
  { name: "imagination", value: 3 },
  { name: "in the flesh", value: 3 },
  { name: "capable", value: 3 },
  { name: "funny", value: 3 },
  { name: "choose", value: 6 },
  { name: "One day", value: 3 },
];

var originDataLife = [
  { name: "Ha ha ha ha", value: 1027 },
  { name: "Xiaochao", value: 45 },
  { name: "two", value: 40 },
  { name: "A little bit", value: 37 },
  { name: "things", value: 31 },
  { name: "once", value: 27 },
  { name: "not that much", value: 18 },
  { name: "show", value: 17 },
  { name: "gaussian", value: 17 },
  { name: "effect", value: 16 },
  { name: "lovely", value: 14 },
  { name: "refuse", value: 14 },
  { name: "self-detonation", value: 12 },
  { name: "full power", value: 12 },
  { name: "I can", value: 12 },
  { name: "employees", value: 11 },
  { name: "a little proud", value: 11 },
  { name: "machine", value: 11 },
  { name: "surrender to the trap", value: 10 },
  { name: "girlfriend", value: 18 },
  { name: "similar", value: 9 },
  { name: "The dean", value: 8 },
  { name: "a poor lie reveals the truth", value: 8 },
  { name: "Woo hoo", value: 8 },
  { name: "prince", value: 10 },
  { name: "Ultraman,", value: 7 },
  { name: "Yesterday once more", value: 7 },
  { name: "Lower the voice", value: 11 },
  { name: "know", value: 6 },
  { name: "work", value: 6 },
  { name: "The king", value: 6 },
  { name: "food", value: 6 },
  { name: "EQ", value: 5 },
  { name: "be bullied", value: 5 },
  { name: "sausage", value: 5 },
  { name: "none", value: 5 },
  { name: "twelve", value: 5 },
  { name: "Plummer scores twice", value: 5 },
  { name: "sky", value: 4 },
  { name: "azure", value: 4 },
  { name: "identical", value: 4 },
  { name: "Help!", value: 4 },
  { name: "infantry", value: 4 },
  { name: "brother", value: 4 },
  { name: "handsome", value: 4 },
  { name: "cotton", value: 4 },
  { name: "Beauty Filter", value: 3 },
  { name: "Out of the window", value: 3 },
  { name: "papercranes", value: 3 },
  { name: "Come back", value: 3 },
  { name: "full", value: 3 },
  { name: "house", value: 3 },
  { name: "invisible", value: 3 },
  { name: "out loud", value: 3 },
  { name: "What a guy", value: 3 },
  { name: "suitable", value: 3 },
  { name: "boss", value: 3 },
  { name: "really", value: 3 },
  { name: "very", value: 3 },
  { name: "video", value: 3 },
  { name: "bullet chat", value: 3 },
  { name: "gadgets", value: 3 },
  { name: "The following", value: 3 },
  { name: "like", value: 3 },
  { name: "child", value: 3 },
  { name: "directly", value: 3 },
  { name: "There have been", value: 2 },
  { name: "kowtow", value: 2 },
  { name: "A little", value: 2 },
  { name: "College students'", value: 2 },
  { name: "Activity center", value: 2 },
  { name: "Little thing", value: 2 },
  { name: "youth", value: 2 },
  { name: "Can't", value: 2 },
  { name: "Is there any", value: 2 },
  { name: "think", value: 2 },
  { name: "As if", value: 2 },
  { name: "pain", value: 2 },
  { name: "war", value: 2 },
  { name: "sequelae", value: 2 },
  { name: "farmer", value: 2 },
  { name: "Turns out", value: 2 },
];

var originDataGame = [
  { name: "hard work", value: 202 },
  { name: "game", value: 136 },
  { name: "Ha ha ha", value: 144 },
  { name: "really", value: 76 },
  { name: "hours", value: 62 },
  { name: "What a guy", value: 61 },
  { name: "comrade", value: 51 },
  { name: "Insects.", value: 51 },
  { name: "The protagonist", value: 48 },
  { name: "directly", value: 47 },
  { name: "Thank you", value: 75 },
  { name: "feeling", value: 43 },
  { name: "There are", value: 43 },
  { name: "The world", value: 42 },
  { name: "Ура!", value: 41 },
  { name: "The progress bar", value: 40 },
  { name: "know", value: 39 },
  { name: "now", value: 38 },
  { name: "Should be", value: 37 },
  { name: "Actually,", value: 36 },
  { name: "Oh my god", value: 36 },
  { name: "Don't", value: 57 },
  { name: "Strikebreaker", value: 32 },
  { name: "see", value: 31 },
  { name: "already", value: 31 },
  { name: "What is this", value: 30 },
  { name: "A little bit", value: 30 },
  { name: "Tears eye", value: 30 },
  { name: "workers", value: 29 },
  { name: "subscribe, like and share", value: 29 },
  { name: "video", value: 28 },
  { name: "two", value: 28 },
  { name: "up", value: 28 },
  { name: "maybe", value: 28 },
  { name: "real", value: 53 },
  { name: "The Soviet Union", value: 28 },
  { name: "localization", value: 27 },
  { name: "This kind", value: 26 },
  { name: "The movie", value: 26 },
  { name: "The last", value: 26 },
  { name: "someone", value: 26 },
  { name: "The union", value: 26 },
  { name: "ghost", value: 25 },
  { name: "capital", value: 25 },
  { name: "think", value: 25 },
  { name: "As if", value: 23 },
  { name: "goodbye", value: 23 },
  { name: "dubbing", value: 23 },
  { name: "awesome", value: 22 },
  { name: "Next time", value: 21 },
  { name: "Grey domain", value: 20 },
  { name: "Harry", value: 20 },
  { name: "The Chernobyl", value: 20 },
  { name: "incredibly", value: 19 },
  { name: "In front", value: 19 },
  { name: "The original", value: 19 },
  { name: "red", value: 19 },
  { name: "appear", value: 19 },
  { name: "bullet chat", value: 19 },
  { name: "A certain", value: 19 },
  { name: "must be", value: 19 },
  { name: "touched", value: 18 },
  { name: "completely", value: 18 },
  { name: "forever", value: 18 },
  { name: "a lot", value: 18 },
  { name: "China", value: 18 },
  { name: "millions", value: 18 },
  { name: "human", value: 17 },
  { name: "society", value: 17 },
  { name: "You mean", value: 17 },
  { name: "Need", value: 17 },
  { name: "tequila", value: 16 },
  { name: "Stand up", value: 16 },
  { name: "all", value: 16 },
  { name: "irony", value: 16 },
  { name: "thought", value: 16 },
  { name: "The child", value: 16 },
  { name: "The story", value: 16 },
  { name: "The plot", value: 16 },
  { name: "-lism", value: 15 },
  { name: "hardcore", value: 15 },
  { name: "like", value: 15 },
  { name: "place", value: 15 },
  { name: "Isn't it", value: 14 },
  { name: "The United States", value: 14 },
  { name: "All over the world", value: 14 },
  { name: "A sigh of relief", value: 14 },
  { name: "The ending", value: 14 },
  { name: "All of a sudden", value: 14 },
  { name: "brother", value: 14 },
  { name: "before", value: 14 },
  { name: "Come back", value: 14 },
];